module.exports = {
  Ping: require('./ping'),
  ArgsInfo: require('./args-info'),
  Help: require('./help'),
  Commands: require('./commands'),
  Addition: require('./addition'),
  Math: require('./math'),
  Hangman: require('./calc'),
  Guess: require('./guess'),
  Emoji: require('./emoticon'),
  Singlegame: require('./singlegame'),
  Multigame: require('./multigame'),
  Roll: require('./roll'),
  Multiroll: require('./multiroll'),
  Usless: require('./usless'),
  Reverse: require('./reverse'),
  Motivation: require('./motivation'),
  RandomQuotes: require('./randomquotes'),
  rGif: require('./rGif'),
}
